name: flutter_l10n_app
description: "Flutter example project with l10n."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.6.0"

dependencies:
  drift: ^2.22.1
  drift_dev: ^2.22.1
  drift_flutter: ^0.2.2
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  fpdart: ^1.1.1
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.5
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
